config/routes.rb
Rails.application.routes.draw do
  # devise routes
  devise_for :users

  # my routes
  get 'home/index'
  root 'home#index'

  # items routes
  get '/items/:id', to: 'items#show'

  # favorites routes
  post '/favourites', to: 'favourites#create'
  get '/favourites', to: 'favourites#index'
  get '/favourites/:id', to: 'favourites#show'
  delete '/favourites', to: 'favourites#destroy'

  # user activity routes
  get '/user_activity', to: 'user_activity#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user_id, presence: true
  validates :product_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :favourites

  # Returned JSON from LCBO has a lot of extra content we don't use
  ALLOWED_ATTRIBUTES = self.attribute_names.map{ |attr| attr.to_sym }

  def self.cleanup_product_hash(product_hash)
    product_hash.delete_if { |k, _| !ALLOWED_ATTRIBUTES.include?(k) }
    product_hash
  end

  def get_price_in_dollars
    price_in_cents.to_f / 100
  end

  def alcohol_content_in_percent
    alcohol_content.to_f / 100
  end

  def self.bulk_add_if_necessary(products)
    products = products.map{ |product| cleanup_product_hash(product) }
    product_ids = products.map{ |product| product[:id] }
    existing_records = Product.where(id: product_ids).collect(&:id)
    remaining = product_ids - existing_records
    products = products.select{ |product| remaining.include?(product[:id]) }
    products.each do |product|
      p = Product.new(product)
      p.save!
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favourites
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
  enum action: [:product_view, :product_favorite, :product_unfavorite]
  validates :user_id, presence: true
  validates :object_id, presence: true
  validates :action, presence: true
  validates :time_performed, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    update_attrs = [:password, :password_confirmation, :current_password]
    devise_parameter_sanitizer.permit(:account_update, keys: update_attrs)
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favourites = User.find(current_user.id).favourites.map{
        |f| f.product
    }
  end

  def create
    @favourite = Favourite.new(user_id: favourite_params[:user_id],
                               product_id: favourite_params[:product_id]).save!
    UserActivity.new(
        user_id: current_user.id,
        object_id: favourite_params[:product_id],
        action: UserActivity.actions[:product_favorite],
        time_performed: Time.now.utc
    ).save!
    redirect_to "/items/#{favourite_params[:product_id]}"
  end

  def show
    redirect_to "/items/#{params[:product_id]}"
  end

  def destroy
    f = Favourite.where(user_id: favourite_params[:user_id],
                        product_id: favourite_params[:product_id])
    if f.present?
      f.destroy_all
      redirect_to "/items/#{params[:product_id]}"
    else
      render json: {error: 'Could not find favourite'},
             status: :not_found
    end
  end

  private

  def favourite_params
    params.permit(:user_id, :product_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    c = Service::Lcbo::Client.new
    @products = Rails.cache.fetch(
        search_cache_key(search_params[:search], 20, search_params[:per_page]),
        expires_in: 1.hour) do
      c.search(search_params[:search],
               20, search_params[:page])
    end
    @query = search_params[:search]
    @next_page = params[:page].to_i + 1
    Product.bulk_add_if_necessary(@products)
    @products = Product.where(id: @products.map{ |p| p[:id] })
  end

  private
  def search_params
    params.permit(:search, :page)
  end

  def search_cache_key(query, per_page, page)
    "#{URI::encode(query||'')}-#{per_page.to_s}-#{page.to_s}"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  ## Item detail view
  def show
    # Check if item in DB first before making a call
    @product = Product.find_by_id(item_params[:id])
    if @product.nil?
      # create the product by fetching from LCBO API and then displaying it
      c = Service::Lcbo::Client.new
      product_hash = c.product(item_params[:id])

      # If we visit the URL manually this could happen
      if product_hash.nil?
        render json: { error: 'Could not find product on LCBO' },
               status: :not_found
        return
      end

      # clean up the hash from all the extra data we don't need
      product_hash = Product.cleanup_product_hash(product_hash)
      @product = Product.new(product_hash)
      if !@product.save
        # something went wrong
        render json: { error: 'Could not process product'},
               status: :unprocessable_entity
        return
      end
    end
    if user_signed_in?
      # log view of product
      UserActivity.new(
                      user_id: current_user.id,
                      object_id: @product.id,
                      action: UserActivity.actions[:product_view],
                      time_performed: Time.now.utc
      ).save!
    end
  end

  private

  def item_params
    params.permit(:id)
  end
end

app/controllers/user_activity_controller.rb
class UserActivityController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_activities = UserActivity.where(user_id: current_user.id)
    @activities_by_action = ActiveRecord::Base.connection.execute(
        'select object_id, action, count(object_id) from user_activities where user_id = 1 group by object_id, action'
    ).map{ |row| row.symbolize_keys }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_activity_helper.rb
module UserActivityHelper

  def action_to_s(action)
    case action
      when 0
        "Viewed Item"
      when 1
        "Favourited Item"
      when 2
        "Unfavourited Item"
      else
        "Unknown action"
    end
  end
end

app/views/favourites/create.html.erb
<h1>Favourites#create</h1>
<p>Find me in app/views/favourites/create.html.erb</p>

app/views/favourites/destroy.html.erb
<h1>Favourites#destroy</h1>
<p>Find me in app/views/favourites/destroy.html.erb</p>

app/views/favourites/index.html.erb
<h1>Your Favourites</h1>

<table class="table table-bordered">
  <thead>
  <tr>
    <th></th>
    <th>Product Name</th>
    <th>Price</th>
    <th>Alcohol Content(%)</th>
    <th>Variety/Style</th>
    <th>Volume (ml)</th>
  </tr>
  </thead>
  <tbody>
  <% @favourites.each do |favorite| %>
      <tr>
        <th scope="row" align="center">
          <a href="<%= favorite.image_thumb_url %>">
            <img src="<%= favorite.image_thumb_url %>" style="width: 128px; height: 128px;"/>
          </a>
        </th>
        <th><%= link_to favorite.name, "/items/#{favorite.id}" %></th>
        <th><%= favorite.get_price_in_dollars %></th>
        <th><%= favorite.alcohol_content_in_percent %></th>
        <% if favorite.varietal.present? %>
            <th><%= favorite.varietal %></th>
        <% else %>
            <th><%= favorite.style %></th>
        <% end %>
        <th><%= favorite.volume_in_milliliters %></th>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/favourites/show.html.erb
<h1>Favourites#show</h1>
<p>Find me in app/views/favourites/show.html.erb</p>

app/views/home/index.html.erb
<div class="container">
  <div class="input-group input-group-lg">
    <%= form_tag home_index_path, method: :get, class: 'form-control' do %>
        <p>
          <%= text_field_tag :search %>
          <%= hidden_field_tag :page, 1 %>
          <%= submit_tag "Search", class: 'btn btn-primary btn-success' %>
        </p>
    <% end %>
  </div>

  <div class="pull-left">
    <% if @products.present? %>
        <%= form_tag home_index_path, method: :get do %>
            <p>
              <%= hidden_field_tag :page, @next_page %>
              <%= hidden_field_tag :search, @query %>
              <%= submit_tag 'Next page', class: 'btn btn-primary btn-success' %>
            </p>
        <% end %>
    <% end %>
  </div>
</div>

<div class="container">

  <div id="products" class="row list-group">
    <% @products.each do |product| %>
        <div class="item col-xs-6 col-lg-6">
          <div class="thumbnail">
            <a href="<%= product.image_thumb_url %>">
              <img src="<%= product.image_thumb_url %>" style="width: 128px; height: 128px;"/>
            </a>
            <div class="caption">
              <h4 class="group inner list-group-item-heading">
                <%= link_to product.name, "/items/#{product.id}" %>
              </h4>
              <p class="group inner list-group-item-text">
                <%= product.alcohol_content_in_percent %> % (Alcohol Content)
                | Variety: <%= product.varietal %>
                | <%= product.volume_in_milliliters %>ml
              </p>
              <div class="row">
                <div class="col-xs-12 col-md-6">
                  <p class="lead">
                    $<%= product.get_price_in_dollars %>
                  </p>
                </div>

                <% if user_signed_in? %>
                    <div class="col-xs-12 col-md-6">
                      <% if Favourite.where(user_id: current_user.id, product_id: product.id).empty? %>
                          <%= form_tag favourites_path, method: :post do %>
                              <p>
                                <%= hidden_field_tag :user_id, current_user.id %>
                                <%= hidden_field_tag :product_id, product.id %>
                                <%= submit_tag "Add to Favourites", class: 'btn btn-primary btn-success' %>
                              </p>
                          <% end %>
                      <% else %>
                          <%= form_tag favourites_path, method: :delete do %>
                              <p>
                                <%= hidden_field_tag :user_id, current_user.id %>
                                <%= hidden_field_tag :product_id, product.id %>
                                <%= submit_tag "Remove from Favourites", class: 'btn btn-primary btn-danger' %>
                              </p>
                          <% end %>
                      <% end %>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <div class="pull-right">
    <% if @products.present? %>
        <%= form_tag home_index_path, method: :get do %>
            <p>
              <%= hidden_field_tag :page, @next_page %>
              <%= hidden_field_tag :search, @query %>
              <%= submit_tag 'Next page', class: 'btn btn-primary btn-success' %>
            </p>
        <% end %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="media">
    <div class="media-left">
      <img src="<%= @product.image_url %>" style="width: 480px; height: 640px;"/>
    </div>

    <div class="media-body">
      <h4 class="media-heading"><%= @product.name %></h4>
      <ul class="list-group">
        <li class="list-group-item">
          Alcohol Content: <%= @product.alcohol_content_in_percent %> %
        </li>
        <li class="list-group-item">
          Origin: <%= @product.origin %>
        </li>
        <li class="list-group-item">
          Price: $<%= @product.price_in_cents.to_f / 100 %>
        </li>
        <% if @product.description.present? %>
            <li class="list-group-item">
              <%= @product.description %>
            </li>
        <% end %>
        <% if @product.varietal.present? %>
            <li class="list-group-item">
              <%= @product.varietal %>
            </li>
        <% end %>
        <% if @product.style.present? %>
            <li class="list-group-item">
              <%= @product.style %>
            </li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
          <% if Favourite.where(user_id: current_user.id, product_id: @product.id).empty? %>
              <%= form_tag favourites_path, method: :post do %>
                  <p>
                    <%= hidden_field_tag :user_id, current_user.id %>
                    <%= hidden_field_tag :product_id, @product.id %>
                    <%= submit_tag "Add to Favourites", class: 'btn btn-primary btn-success' %>
                  </p>
              <% end %>
          <% else %>
              <%= form_tag favourites_path, method: :delete do %>
                  <p>
                    <%= hidden_field_tag :user_id, current_user.id %>
                    <%= hidden_field_tag :product_id, @product.id %>
                    <%= submit_tag "Remove from Favourites", class: 'btn btn-primary btn-danger' %>
                  </p>
              <% end %>
          <% end %>
      <% else %>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default"><%= link_to "Sign Up", new_user_registration_path %></button>
        <button type="button" class="btn btn-default"><%= link_to "Sign In", new_user_session_path %></button>
      </div>
      <% end %>
    </div>


  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Social Footer, Single Coloured -->
<!-- Include Font Awesome Stylesheet in Header -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<!-- // -->
<footer class="footer">
  <div class="container">
    <div class="text-center center-block">
      <br />
      <a href="https://twitter.com/makramkd"><i class="fa fa-twitter-square fa-3x social"></i></a>
      <a href="https://github.com/makramkd"><i class="fa fa-github fa-3x social"></i></a>
    </div>
    <hr />
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">LCBO Shopper</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            <li><a href="/favourites">Favourites <span class="sr-only">(current)</span></a></li>
            <li><a href="/user_activity">Activity</a></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/user_activity/index.html.erb
<div class="container">
  <h2>My Activity</h2>
  <div class="row">
    <div class="col-xs-6">
      <ul class="list-group">
        <% @user_activities.each do |activity| %>
            <% if activity.product_view? %>
                <li class="list-group-item">
                  Viewed product <%= link_to Product.find(activity.object_id).name, "/items/#{activity.object_id}" %>
                  at <%= activity.time_performed %>
                </li>
            <% elsif activity.product_favorite? %>
                <li class="list-group-item">
                  Favourited product <%= link_to Product.find(activity.object_id).name, "/items/#{activity.object_id}" %>
                  at <%= activity.time_performed %>
                </li>
            <% elsif activity.product_unfavorite? %>
                <li class="list-group-item">
                  Unfavourited product <%= link_to Product.find(activity.object_id).name, "/items/#{activity.object_id}" %>
                  at <%= activity.time_performed %>
                </li>
            <% end %>
        <% end %>
      </ul>
    </div>

    <div class="col-xs-6">
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th>Product ID</th>
          <th>Product Name</th>
          <th>Action</th>
          <th>Times performed</th>
        </tr>
        </thead>
        <tbody>
        <% @activities_by_action.each do |aba| %>
        <tr>
          <th scope="row"><%= aba[:object_id] %></th>
          <th><%= link_to Product.find_by(id: aba[:object_id]).name, "/items/#{aba[:object_id]}" %></th>
          <th><%= action_to_s(aba[:action]) %></th>
          <th><%= aba[:count] %></th>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>